version: "3"
services:
  database:
    image: mariadb:10.5
    restart: ${RESTART_MODE}
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
    - ${VOLUMES_ROOT_PATH}/database-data:/var/lib/mysql

  bookstack:
    build: ./
    restart: ${RESTART_MODE}
    depends_on:
    - database
    environment:
    - DB_HOST=database:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=${DB_PASSWORD}
    - APP_URL=${APP_URL}
    volumes:
    - ${VOLUMES_ROOT_PATH}/uploads:/var/www/bookstack/public/uploads
    - ${VOLUMES_ROOT_PATH}/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"
