version: "3"
services:
  database:
    image: mariadb:10.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - database-data:/var/lib/mysql

  bookstack:
    build: ./
    depends_on:
    - database
    environment:
    - DB_HOST=database:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    - APP_URL=http://localhost:8080
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

volumes:
 database-data:
 uploads:
 storage-uploads:
